-- Дополнительные объявления по городам (запускать один раз; повторный запуск ничего не дублирует)
BEGIN;
UPDATE owners SET phone = '+79121263013' WHERE name = 'Арендатра';
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'gusenichnyy-ekskavator-naryan-mar'), 1, 24), $q$Гусеничный экскаватор, ковш до 1.2 м³$q$, 'gusenichnyy-ekskavator-naryan-mar', $q$Гусеничный экскаватор для земляных работ. В наличии узкопленочные и болотные гусеницы, слани для работы на болотистой местности. Подача техники по Нарьян-Мару и округу согласуется с менеджером заранее: города округа не связаны постоянной сухопутной дорогой с остальной страной. Типичные задачи в Нарьян-Маре: монтаж и погрузка оборудования на объектах округа; работы в порту и на речных причалах. Почасовая аренда от 8 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2800, 8, $q$Нарьян-Мар$q$, true, now(), now(), $q${"Масса": "до 22 т", "Гусеницы": "узкопленочные и болотные (слани в наличии)", "Объём ковша": "до 1.2 м³"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'gusenichnyy-ekskavator'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'gusenichnyy-ekskavator') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'buldozer-naryan-mar'), 1, 24), $q$Бульдозер, отвал до 5 м³$q$, 'buldozer-naryan-mar', $q$Гусеничный бульдозер для планировки и перемещения грунта, расчистки площадок и снега. Подача техники по Нарьян-Мару и округу согласуется с менеджером заранее: города округа не связаны постоянной сухопутной дорогой с остальной страной. Типичные задачи в Нарьян-Маре: работы в порту и на речных причалах; монтаж и погрузка оборудования на объектах округа. Почасовая аренда от 8 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2800, 8, $q$Нарьян-Мар$q$, true, now(), now(), $q${"Масса": "17 т", "Объём отвала": "до 5 м³", "Ширина гусениц": "110 см"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'buldozer'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'buldozer') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'avtokran-25t-naryan-mar'), 1, 24), $q$Автокран 25 т, стрела 22–33 м$q$, 'avtokran-25t-naryan-mar', $q$Автокран грузоподъёмностью 25 тонн для монтажных и погрузочных работ. Полноприводное шасси 6х6 — работает вне асфальтированных дорог. Подача техники по Нарьян-Мару и округу согласуется с менеджером заранее: города округа не связаны постоянной сухопутной дорогой с остальной страной. Типичные задачи в Нарьян-Маре: строительство и ремонт зданий, дорог и инженерных сетей; подсыпка и обустройство площадок. Почасовая аренда от 8 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2700, 8, $q$Нарьян-Мар$q$, true, now(), now(), $q${"Шасси": "вездеход (6х6)", "Длина стрелы": "22–33 м", "Грузоподъёмность": "25 т"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'avtokran-25t'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'avtokran-25t') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'vahtovyy-avtobus-harjaginskiy'), 1, 24), $q$Вахтовый автобус, 22–28 мест$q$, 'vahtovyy-avtobus-harjaginskiy', $q$Вахтовый автобус повышенной проходимости для перевозки бригад на объекты по грунтовым дорогам и зимникам. Харьягинский — вахтовый посёлок, поэтому маршрут и въезд на объект согласуются с менеджером при подтверждении заявки. Типичные задачи в Харьягинском: перевозка вахтовых бригад; монтаж и погрузка оборудования. Почасовая аренда от 4 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2550, 4, $q$Харьягинский$q$, true, now(), now(), $q${"Шасси": "вездеход (6х6)", "Вместимость": "22–28 мест"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'vahtovyy-avtobus'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'vahtovyy-avtobus') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'avtokran-25t-harjaginskiy'), 1, 24), $q$Автокран 25 т, стрела 22–33 м$q$, 'avtokran-25t-harjaginskiy', $q$Автокран грузоподъёмностью 25 тонн для монтажных и погрузочных работ. Полноприводное шасси 6х6 — работает вне асфальтированных дорог. Харьягинский — вахтовый посёлок, поэтому маршрут и въезд на объект согласуются с менеджером при подтверждении заявки. Типичные задачи в Харьягинском: обслуживание промысловых объектов и площадок; монтаж и погрузка оборудования. Почасовая аренда от 8 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2700, 8, $q$Харьягинский$q$, true, now(), now(), $q${"Шасси": "вездеход (6х6)", "Длина стрелы": "22–33 м", "Грузоподъёмность": "25 т"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'avtokran-25t'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'avtokran-25t') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'gusenichnyy-ekskavator-harjaginskiy'), 1, 24), $q$Гусеничный экскаватор, ковш до 1.2 м³$q$, 'gusenichnyy-ekskavator-harjaginskiy', $q$Гусеничный экскаватор для земляных работ. В наличии узкопленочные и болотные гусеницы, слани для работы на болотистой местности. Харьягинский — вахтовый посёлок, поэтому маршрут и въезд на объект согласуются с менеджером при подтверждении заявки. Типичные задачи в Харьягинском: земляные работы при обустройстве площадок; перевозка вахтовых бригад. Почасовая аренда от 8 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2800, 8, $q$Харьягинский$q$, true, now(), now(), $q${"Масса": "до 22 т", "Гусеницы": "узкопленочные и болотные (слани в наличии)", "Объём ковша": "до 1.2 м³"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'gusenichnyy-ekskavator'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'gusenichnyy-ekskavator') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'buldozer-harjaginskiy'), 1, 24), $q$Бульдозер, отвал до 5 м³$q$, 'buldozer-harjaginskiy', $q$Гусеничный бульдозер для планировки и перемещения грунта, расчистки площадок и снега. Харьягинский — вахтовый посёлок, поэтому маршрут и въезд на объект согласуются с менеджером при подтверждении заявки. Типичные задачи в Харьягинском: перевозка вахтовых бригад; земляные работы при обустройстве площадок. Почасовая аренда от 8 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2800, 8, $q$Харьягинский$q$, true, now(), now(), $q${"Масса": "17 т", "Объём отвала": "до 5 м³", "Ширина гусениц": "110 см"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'buldozer'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'buldozer') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'gusenichnyy-ekskavator-usinsk'), 1, 24), $q$Гусеничный экскаватор, ковш до 1.2 м³$q$, 'gusenichnyy-ekskavator-usinsk', $q$Гусеничный экскаватор для земляных работ. В наличии узкопленочные и болотные гусеницы, слани для работы на болотистой местности. Из Усинска техника уходит на промыслы и отдалённые площадки; маршрут и сроки подачи подтверждает менеджер. Типичные задачи в Усинске: перевозка вахтовых бригад на объекты; устройство временных дорог и зимников. Почасовая аренда от 8 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2800, 8, $q$Усинск$q$, true, now(), now(), $q${"Масса": "до 22 т", "Гусеницы": "узкопленочные и болотные (слани в наличии)", "Объём ковша": "до 1.2 м³"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'gusenichnyy-ekskavator'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'gusenichnyy-ekskavator') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'vahtovyy-avtobus-usinsk'), 1, 24), $q$Вахтовый автобус, 22–28 мест$q$, 'vahtovyy-avtobus-usinsk', $q$Вахтовый автобус повышенной проходимости для перевозки бригад на объекты по грунтовым дорогам и зимникам. Из Усинска техника уходит на промыслы и отдалённые площадки; маршрут и сроки подачи подтверждает менеджер. Типичные задачи в Усинске: устройство временных дорог и зимников; монтаж и перемещение тяжёлого оборудования. Почасовая аренда от 4 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2550, 4, $q$Усинск$q$, true, now(), now(), $q${"Шасси": "вездеход (6х6)", "Вместимость": "22–28 мест"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'vahtovyy-avtobus'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'vahtovyy-avtobus') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'buldozer-usinsk'), 1, 24), $q$Бульдозер, отвал до 5 м³$q$, 'buldozer-usinsk', $q$Гусеничный бульдозер для планировки и перемещения грунта, расчистки площадок и снега. Из Усинска техника уходит на промыслы и отдалённые площадки; маршрут и сроки подачи подтверждает менеджер. Типичные задачи в Усинске: устройство временных дорог и зимников; перевозка вахтовых бригад на объекты. Почасовая аренда от 8 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2800, 8, $q$Усинск$q$, true, now(), now(), $q${"Масса": "17 т", "Объём отвала": "до 5 м³", "Ширина гусениц": "110 см"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'buldozer'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'buldozer') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'avtokran-25t-pechora'), 1, 24), $q$Автокран 25 т, стрела 22–33 м$q$, 'avtokran-25t-pechora', $q$Автокран грузоподъёмностью 25 тонн для монтажных и погрузочных работ. Полноприводное шасси 6х6 — работает вне асфальтированных дорог. Печора — удобная точка для работы в Печорском районе и на соседних северных направлениях. Типичные задачи в Печоре: работы на объектах железной дороги и речного порта; монтаж и погрузка негабаритных грузов. Почасовая аренда от 8 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2700, 8, $q$Печора$q$, true, now(), now(), $q${"Шасси": "вездеход (6х6)", "Длина стрелы": "22–33 м", "Грузоподъёмность": "25 т"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'avtokran-25t'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'avtokran-25t') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'vahtovyy-avtobus-pechora'), 1, 24), $q$Вахтовый автобус, 22–28 мест$q$, 'vahtovyy-avtobus-pechora', $q$Вахтовый автобус повышенной проходимости для перевозки бригад на объекты по грунтовым дорогам и зимникам. Печора — удобная точка для работы в Печорском районе и на соседних северных направлениях. Типичные задачи в Печоре: строительство и ремонт подъездных путей; монтаж и погрузка негабаритных грузов. Почасовая аренда от 4 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2550, 4, $q$Печора$q$, true, now(), now(), $q${"Шасси": "вездеход (6х6)", "Вместимость": "22–28 мест"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'vahtovyy-avtobus'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'vahtovyy-avtobus') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'buldozer-pechora'), 1, 24), $q$Бульдозер, отвал до 5 м³$q$, 'buldozer-pechora', $q$Гусеничный бульдозер для планировки и перемещения грунта, расчистки площадок и снега. Печора — удобная точка для работы в Печорском районе и на соседних северных направлениях. Типичные задачи в Печоре: строительство и ремонт подъездных путей; земляные работы и подготовка площадок. Почасовая аренда от 8 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2800, 8, $q$Печора$q$, true, now(), now(), $q${"Масса": "17 т", "Объём отвала": "до 5 м³", "Ширина гусениц": "110 см"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'buldozer'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'buldozer') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'vahtovyy-avtobus-vorkuta'), 1, 24), $q$Вахтовый автобус, 22–28 мест$q$, 'vahtovyy-avtobus-vorkuta', $q$Вахтовый автобус повышенной проходимости для перевозки бригад на объекты по грунтовым дорогам и зимникам. Воркута расположена за Полярным кругом: на технику и сроки лучше закладывать запас на погоду и состояние дорог. Типичные задачи в Воркуте: подъём грузов и монтаж на объектах за полярным кругом; расчистка территорий и снега. Почасовая аренда от 4 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2550, 4, $q$Воркута$q$, true, now(), now(), $q${"Шасси": "вездеход (6х6)", "Вместимость": "22–28 мест"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'vahtovyy-avtobus'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'vahtovyy-avtobus') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'gusenichnyy-ekskavator-vorkuta'), 1, 24), $q$Гусеничный экскаватор, ковш до 1.2 м³$q$, 'gusenichnyy-ekskavator-vorkuta', $q$Гусеничный экскаватор для земляных работ. В наличии узкопленочные и болотные гусеницы, слани для работы на болотистой местности. Воркута расположена за Полярным кругом: на технику и сроки лучше закладывать запас на погоду и состояние дорог. Типичные задачи в Воркуте: перевозка сотрудников к удалённым объектам; подъём грузов и монтаж на объектах за полярным кругом. Почасовая аренда от 8 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2800, 8, $q$Воркута$q$, true, now(), now(), $q${"Масса": "до 22 т", "Гусеницы": "узкопленочные и болотные (слани в наличии)", "Объём ковша": "до 1.2 м³"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'gusenichnyy-ekskavator'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'gusenichnyy-ekskavator') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'avtokran-25t-vorkuta'), 1, 24), $q$Автокран 25 т, стрела 22–33 м$q$, 'avtokran-25t-vorkuta', $q$Автокран грузоподъёмностью 25 тонн для монтажных и погрузочных работ. Полноприводное шасси 6х6 — работает вне асфальтированных дорог. Воркута расположена за Полярным кругом: на технику и сроки лучше закладывать запас на погоду и состояние дорог. Типичные задачи в Воркуте: ремонт и обслуживание городской и промышленной инфраструктуры; расчистка территорий и снега. Почасовая аренда от 8 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2700, 8, $q$Воркута$q$, true, now(), now(), $q${"Шасси": "вездеход (6х6)", "Длина стрелы": "22–33 м", "Грузоподъёмность": "25 т"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'avtokran-25t'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'avtokran-25t') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'avtokran-25t-uhta'), 1, 24), $q$Автокран 25 т, стрела 22–33 м$q$, 'avtokran-25t-uhta', $q$Автокран грузоподъёмностью 25 тонн для монтажных и погрузочных работ. Полноприводное шасси 6х6 — работает вне асфальтированных дорог. Ухта — крупный промышленный центр, откуда удобно обслуживать объекты в Ухтинском и соседних районах. Типичные задачи в Ухте: строительство и ремонт на предприятиях нефти и газа; земляные работы и обустройство площадок. Почасовая аренда от 8 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2700, 8, $q$Ухта$q$, true, now(), now(), $q${"Шасси": "вездеход (6х6)", "Длина стрелы": "22–33 м", "Грузоподъёмность": "25 т"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'avtokran-25t'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'avtokran-25t') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'gusenichnyy-ekskavator-uhta'), 1, 24), $q$Гусеничный экскаватор, ковш до 1.2 м³$q$, 'gusenichnyy-ekskavator-uhta', $q$Гусеничный экскаватор для земляных работ. В наличии узкопленочные и болотные гусеницы, слани для работы на болотистой местности. Ухта — крупный промышленный центр, откуда удобно обслуживать объекты в Ухтинском и соседних районах. Типичные задачи в Ухте: высотные работы: освещение, опоры, фасады; монтаж оборудования и металлоконструкций. Почасовая аренда от 8 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2800, 8, $q$Ухта$q$, true, now(), now(), $q${"Масса": "до 22 т", "Гусеницы": "узкопленочные и болотные (слани в наличии)", "Объём ковша": "до 1.2 м³"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'gusenichnyy-ekskavator'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'gusenichnyy-ekskavator') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'avtovyshka-agp-uhta'), 1, 24), $q$Автовышка (АГП), стрела до 33 м$q$, 'avtovyshka-agp-uhta', $q$Автогидроподъёмник для высотных работ. Стрела комбинированного типа, люлька грузоподъёмностью до 300 кг. Ухта — крупный промышленный центр, откуда удобно обслуживать объекты в Ухтинском и соседних районах. Типичные задачи в Ухте: высотные работы: освещение, опоры, фасады; земляные работы и обустройство площадок. Почасовая аренда от 8 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2700, 8, $q$Ухта$q$, true, now(), now(), $q${"Тип стрелы": "комбинированная", "Длина стрелы": "до 33 м", "Грузоподъёмность люльки": "до 300 кг"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'avtovyshka-agp'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'avtovyshka-agp') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'avtokran-25t-syktyvkar'), 1, 24), $q$Автокран 25 т, стрела 22–33 м$q$, 'avtokran-25t-syktyvkar', $q$Автокран грузоподъёмностью 25 тонн для монтажных и погрузочных работ. Полноприводное шасси 6х6 — работает вне асфальтированных дорог. Сыктывкар — столица региона: здесь проще всего быстро согласовать технику на городские объекты и в пригороды. Типичные задачи в Сыктывкаре: городское и жилое строительство; монтаж конструкций на производственных площадках. Почасовая аренда от 8 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2700, 8, $q$Сыктывкар$q$, true, now(), now(), $q${"Шасси": "вездеход (6х6)", "Длина стрелы": "22–33 м", "Грузоподъёмность": "25 т"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'avtokran-25t'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'avtokran-25t') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'gusenichnyy-ekskavator-syktyvkar'), 1, 24), $q$Гусеничный экскаватор, ковш до 1.2 м³$q$, 'gusenichnyy-ekskavator-syktyvkar', $q$Гусеничный экскаватор для земляных работ. В наличии узкопленочные и болотные гусеницы, слани для работы на болотистой местности. Сыктывкар — столица региона: здесь проще всего быстро согласовать технику на городские объекты и в пригороды. Типичные задачи в Сыктывкаре: высотные работы и обрезка деревьев; ремонт дорог, благоустройство и инженерные сети. Почасовая аренда от 8 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2800, 8, $q$Сыктывкар$q$, true, now(), now(), $q${"Масса": "до 22 т", "Гусеницы": "узкопленочные и болотные (слани в наличии)", "Объём ковша": "до 1.2 м³"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'gusenichnyy-ekskavator'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'gusenichnyy-ekskavator') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'avtokran-25t-sosnogorsk'), 1, 24), $q$Автокран 25 т, стрела 22–33 м$q$, 'avtokran-25t-sosnogorsk', $q$Автокран грузоподъёмностью 25 тонн для монтажных и погрузочных работ. Полноприводное шасси 6х6 — работает вне асфальтированных дорог. Сосногорск находится рядом с Ухтой, поэтому при необходимости технику можно подобрать и в соседнем городе. Типичные задачи в Сосногорске: работы на промплощадках и объектах газопереработки; монтаж и погрузка оборудования. Почасовая аренда от 8 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2700, 8, $q$Сосногорск$q$, true, now(), now(), $q${"Шасси": "вездеход (6х6)", "Длина стрелы": "22–33 м", "Грузоподъёмность": "25 т"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'avtokran-25t'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'avtokran-25t') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'gusenichnyy-ekskavator-sosnogorsk'), 1, 24), $q$Гусеничный экскаватор, ковш до 1.2 м³$q$, 'gusenichnyy-ekskavator-sosnogorsk', $q$Гусеничный экскаватор для земляных работ. В наличии узкопленочные и болотные гусеницы, слани для работы на болотистой местности. Сосногорск находится рядом с Ухтой, поэтому при необходимости технику можно подобрать и в соседнем городе. Типичные задачи в Сосногорске: земляные работы и подготовка площадок; обслуживание железнодорожной инфраструктуры. Почасовая аренда от 8 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2800, 8, $q$Сосногорск$q$, true, now(), now(), $q${"Масса": "до 22 т", "Гусеницы": "узкопленочные и болотные (слани в наличии)", "Объём ковша": "до 1.2 м³"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'gusenichnyy-ekskavator'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'gusenichnyy-ekskavator') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'buldozer-sosnogorsk'), 1, 24), $q$Бульдозер, отвал до 5 м³$q$, 'buldozer-sosnogorsk', $q$Гусеничный бульдозер для планировки и перемещения грунта, расчистки площадок и снега. Сосногорск находится рядом с Ухтой, поэтому при необходимости технику можно подобрать и в соседнем городе. Типичные задачи в Сосногорске: обслуживание железнодорожной инфраструктуры; земляные работы и подготовка площадок. Почасовая аренда от 8 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2800, 8, $q$Сосногорск$q$, true, now(), now(), $q${"Масса": "17 т", "Объём отвала": "до 5 м³", "Ширина гусениц": "110 см"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'buldozer'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'buldozer') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'legkovye-ts-sosnogorsk'), 1, 24), $q$Легковые ТС до 8 мест$q$, 'legkovye-ts-sosnogorsk', $q$Легковой транспорт для перевозки сотрудников и гостей объекта. Сосногорск находится рядом с Ухтой, поэтому при необходимости технику можно подобрать и в соседнем городе. Типичные задачи в Сосногорске: монтаж и погрузка оборудования; обслуживание железнодорожной инфраструктуры. Почасовая аренда от 4 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 1200, 4, $q$Сосногорск$q$, true, now(), now(), $q${"Вместимость": "до 8 мест"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'legkovye-ts'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'legkovye-ts') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'vahtovyy-avtobus-kozhva'), 1, 24), $q$Вахтовый автобус, 22–28 мест$q$, 'vahtovyy-avtobus-kozhva', $q$Вахтовый автобус повышенной проходимости для перевозки бригад на объекты по грунтовым дорогам и зимникам. Кожва — небольшой посёлок в Печорском районе, часто техника подаётся из соседней Печоры; условия подачи уточняет менеджер. Типичные задачи в Кожве: расчистка и планировка территорий; перевозка бригад на объекты по грунтовым дорогам. Почасовая аренда от 4 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2550, 4, $q$Кожва$q$, true, now(), now(), $q${"Шасси": "вездеход (6х6)", "Вместимость": "22–28 мест"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'vahtovyy-avtobus'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'vahtovyy-avtobus') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'gusenichnyy-ekskavator-kozhva'), 1, 24), $q$Гусеничный экскаватор, ковш до 1.2 м³$q$, 'gusenichnyy-ekskavator-kozhva', $q$Гусеничный экскаватор для земляных работ. В наличии узкопленочные и болотные гусеницы, слани для работы на болотистой местности. Кожва — небольшой посёлок в Печорском районе, часто техника подаётся из соседней Печоры; условия подачи уточняет менеджер. Типичные задачи в Кожве: подъём и перемещение грузов на площадках; расчистка и планировка территорий. Почасовая аренда от 8 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2800, 8, $q$Кожва$q$, true, now(), now(), $q${"Масса": "до 22 т", "Гусеницы": "узкопленочные и болотные (слани в наличии)", "Объём ковша": "до 1.2 м³"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'gusenichnyy-ekskavator'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'gusenichnyy-ekskavator') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO vehicles (id, title, slug, description, "pricePerHour", "minHours", city, "isActive", "createdAt", "updatedAt", attributes, "categoryId", "ownerId")
SELECT 'c' || substr(md5(random()::text || clock_timestamp()::text || 'buldozer-kozhva'), 1, 24), $q$Бульдозер, отвал до 5 м³$q$, 'buldozer-kozhva', $q$Гусеничный бульдозер для планировки и перемещения грунта, расчистки площадок и снега. Кожва — небольшой посёлок в Печорском районе, часто техника подаётся из соседней Печоры; условия подачи уточняет менеджер. Типичные задачи в Кожве: расчистка и планировка территорий; подъём и перемещение грузов на площадках. Почасовая аренда от 8 ч, работа по договору, наличный и безналичный расчёт, техника с документами, обученный персонал.$q$, 2800, 8, $q$Кожва$q$, true, now(), now(), $q${"Масса": "17 т", "Объём отвала": "до 5 м³", "Ширина гусениц": "110 см"}$q$::jsonb,
  (SELECT id FROM categories WHERE slug = 'buldozer'), (SELECT id FROM owners WHERE name = 'Арендатра' ORDER BY "createdAt" LIMIT 1)
WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'buldozer') AND EXISTS (SELECT 1 FROM owners WHERE name = 'Арендатра')
ON CONFLICT (slug) DO NOTHING;
COMMIT;
SELECT city, count(*) AS machines FROM vehicles WHERE "isActive" GROUP BY city ORDER BY city;
